-- MySQL Script generated by MySQL Workbench
-- 05/10/16 12:26:55
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HuntNet_DB
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HuntNet_DB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HuntNet_DB` DEFAULT CHARACTER SET utf8 ;
USE `HuntNet_DB` ;

-- -----------------------------------------------------
-- Table `HuntNet_DB`.`Dispositivo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HuntNet_DB`.`Dispositivo` (
  `ip` VARCHAR(15) NOT NULL,
  `comunidad` VARCHAR(80) NOT NULL,
  `addedDate` DATE NOT NULL,
  PRIMARY KEY (`ip`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HuntNet_DB`.`Administrador`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HuntNet_DB`.`Administrador` (
  `idAdministrador` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NOT NULL,
  `contrasenia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idAdministrador`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
