package com.huntnet.entity;
// Generated 5/05/2016 02:12:17 PM by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Administrador generated by hbm2java
 */
@Entity
@Table(name = "administrador", catalog = "huntnet_db")
public class Administrador implements java.io.Serializable {

    private Integer idAdministrador;
    private String correo;
    private String contrasenia;

    public Administrador() {
    }

    public Administrador(String correo, String contrasenia) {
        this.correo = correo;
        this.contrasenia = contrasenia;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "idAdministrador", unique = true, nullable = false)
    public Integer getIdAdministrador() {
        return this.idAdministrador;
    }

    public void setIdAdministrador(Integer idAdministrador) {
        this.idAdministrador = idAdministrador;
    }

    @Column(name = "correo", nullable = false, length = 45)
    public String getCorreo() {
        return this.correo;
    }

    public void setCorreo(String correo) {
        this.correo = correo;
    }

    @Column(name = "contrasenia", nullable = false, length = 45)
    public String getContrasenia() {
        return this.contrasenia;
    }

    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }

}
