package com.huntnet.entity;
// Generated 5/05/2016 02:12:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dispositivo generated by hbm2java
 */
@Entity
@Table(name = "dispositivo", catalog = "huntnet_db")
public class Dispositivo implements java.io.Serializable {

    private Integer idDispositivo;
    private String ip;
    private String comunidad;
    private Date addedDate;

    public Dispositivo() {
    }

    public Dispositivo(String ip, String comunidad, Date addedDate) {
        this.ip = ip;
        this.comunidad = comunidad;
        this.addedDate = addedDate;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "idDispositivo", unique = true, nullable = false)
    public Integer getIdDispositivo() {
        return this.idDispositivo;
    }

    public void setIdDispositivo(Integer idDispositivo) {
        this.idDispositivo = idDispositivo;
    }

    @Column(name = "ip", nullable = false, length = 15)
    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    @Column(name = "comunidad", nullable = false, length = 80)
    public String getComunidad() {
        return this.comunidad;
    }

    public void setComunidad(String comunidad) {
        this.comunidad = comunidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "addedDate", nullable = false, length = 10)
    public Date getAddedDate() {
        return this.addedDate;
    }

    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

}
