package com.huntnet.entity;
// Generated 5/05/2016 02:12:17 PM by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Dispositivo generated by hbm2java
 */
@Entity
@Table(name = "dispositivo", catalog = "huntnet_db")
public class Dispositivo implements java.io.Serializable {

    private String ip;
    private String comunidad;
    private Date addedDate;
    private Integer tcp;
    private Integer udp;
    private Integer icmp;
    private Integer cpu;

    @Column(name = "tcp", nullable = true)
    public Integer getTcp() {
        return tcp;
    }

    public void setTcp(Integer tcp) {
        this.tcp = tcp;
    }

    @Column(name = "udp", nullable = true)
    public Integer getUdp() {
        return udp;
    }

    public void setUdp(Integer udp) {
        this.udp = udp;
    }

    @Column(name = "icmp", nullable = true)
    public Integer getIcmp() {
        return icmp;
    }

    public void setIcmp(Integer icmp) {
        this.icmp = icmp;
    }

    @Column(name = "cpu", nullable = true)
    public Integer getCpu() {
        return cpu;
    }

    public void setCpu(Integer cpu) {
        this.cpu = cpu;
    }

    public Dispositivo() {
    }

    public Dispositivo(String ip, String comunidad, Date addedDate) {
        this.ip = ip;
        this.comunidad = comunidad;
        this.addedDate = addedDate;
    }

    @Id
    @Column(name = "ip", unique = true, nullable = false, length = 15)
    public String getIp() {
        return this.ip;
    }

    public void setIp(String ip) {
        this.ip = ip;
    }

    @Column(name = "comunidad", nullable = false, length = 80)
    public String getComunidad() {
        return this.comunidad;
    }

    public void setComunidad(String comunidad) {
        this.comunidad = comunidad;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "addedDate", nullable = false, length = 10)
    public Date getAddedDate() {
        return this.addedDate;
    }

    public void setAddedDate(Date addedDate) {
        this.addedDate = addedDate;
    }

}
